#SPDX-License-Identifier: MIT-0
---
# tasks file for secure_jump_host
- name: Add unprivilged users
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: "{{ item.value.shell }}"
  loop: "{{ users }}"
  


# - name: Secure ssh

# - name: Set login definitions

# - name: Add bootloader password

# - name: Configure password policies

# - name: Set firewall rules