#SPDX-License-Identifier: MIT-0
---
# tasks file for ssh

- name: Set port

- name: Enable 2FA

- name: Use up-to-date alogrithms

- name: Prohibit root login

- name: prohibti password login

- name: Configure fail2ban